### ISSUE TITLE
Agregar registros

### ISSUE THREAD

**Issue by Juan7655** [Juan7655/bicicleteria#1]
La idea es crear registros con los que se puedan hacer las queries y pruebas de información pertinentes.

**Comment by Juan7655** [comment]
Registros agregados.

**Comment by npinmor** [comment]
Ya se agregaron registros a todas las tablas. Falta revisar que los últimos no presenten errores

**Comment by Juan7655** [comment]
Perfecto. Todos los registros funcionan perfectamente. @npinmor  :+1:
